name: Build Code

on:
  push:
  # pull_request: # Only makes sense if `push` is disabled or enabled only on some branches
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

# Allow one concurrent deployment
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:

  all-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Client Build
        run: make client-build

      - name: Server Build
        run: make server-build

